### ISSUE TITLE
Machine-In-The-Middle (1 high severity vulnerability)

### ISSUE THREAD

**Issue by t16n** [Its-Alex/winston-node-sentry#3]
https-proxy-agent inside the sentry/node package is very outdated.
@sentry/node is quite old in this project. The latest version is "@sentry/node": "^5.7.1",

> winston-node-sentry >  @sentry/node > https-proxy-agent 

To update the new API needs to be met. There were some changes inside sentry between version 4 and 5.

**Comment by t16n** [comment]
https://github.com/Its-Alex/winston-node-sentry/pull/4 Should fix the issues. I am not sure if everything works as expected with the new API from Sentry.

**Comment by Its-Alex** [comment]
I will test it and see if this break the current use, thanks !

**Comment by Its-Alex** [comment]
Fixed in https://github.com/Its-Alex/winston-node-sentry/pull/4

Thanks for your PR !
